# Use root/example as user/password credentials
version: "3.1"

services:
  server:
    image: golang:1.17-alpine
    ports:
      - 8080:8080
    volumes:
      - .:/internal/trips
    working_dir: /internal/trips
    environment:
      MONGO_HOST: mongodb
      MONGO_DATABASE: river-right
      MONGO_PORT: 27017
      MONGO_USERNAME: riverRat
      MONGO_PASSWORD: Password123
    command: sh -c "go run internal/trips/main.go server"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: river-right
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret123
    volumes:
      - ./dev/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SuperSecret123
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  mongo-data:
    driver: local