version: "3.1"

services:
  server:
    image: golang:1.17-alpine
    ports:
      - 8080:8080
    volumes:
      - ./internal:/internal
    working_dir: /internal/trips
    command: sh -c "go run main.go server"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: groups
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SuperSecret789
    volumes:
      - ./dev/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: SuperSecret789

volumes:
  mongo-data:
    driver: local